---
ansible_connection: network_cli
ansible_network_os: routeros
ansible_user: ansible
ansible_password: password
ansible_ssh_pass: password
ansible_become: yes
ansible_become_method: enable
ansible_become_password: password
