---
- name: Display resource statistics (routeros)
  connection: network_cli
  gather_facts: false
  hosts: mikrotik
  tasks:
    - name: Get info
      routeros_command:
        commands: /system resource print
      register: routeros_resources
